/* Command file to read ASCII data file into SAS /*
/* Note 1: change SAS library and dataset name as necessary */
LIBNAME ADAMS1'c:\adams1\sas\';
DATA ADAMS1.Adams1AF_CH;

/* Note 2: change location of input data file to match your system */

INFILE 'c:\adams1\data\ADAMS1AF_CH.da' LRECL = 38;
INPUT
   HHID $ 1 - 6
   PN $ 7 - 9
   AFCNUM  10 - 11
   ADAMSSID $ 12 - 16
   AFCHILD $ 17 - 21
   AFCRELAT  22 - 22
   AFCLIVING  23 - 23
   AFCAGE  24 - 26
   AFCMEDPX  27 - 27
   AFCMEMPX  28 - 28
   AFCAGEPX  29 - 31
   AFCSUDDEN  32 - 32
   AFCWORSEN  33 - 33
   AFCLIMITS  34 - 34
   AFCDRDX  35 - 35
   AFCDXSPECCD  36 - 37
   AFCAUTOP  38 - 38
;

LABEL
   HHID = "HOUSEHOLD IDENTIFIER"
   PN = "PERSON NUMBER"
   AFCNUM = "CHILD NUMBER"
   ADAMSSID = "ADAMS SUBJECT IDENTIFIER"
   AFCHILD = "CHILD NUMBER AS CODED ON CHART"
   AFCRELAT = "RELATIONSHIP OF CHILD TO SUBJECT"
   AFCLIVING = "IS CHILD LIVING OR DECEASED"
   AFCAGE = "CURRENT AGE OR AGE AT DEATH OF CHILD"
   AFCMEDPX = "DID CHILD HAVE A MEDICAL PROBLEM"
   AFCMEMPX = "DID CHILD EVER HAVE MEMORY PROBLEMS"
   AFCAGEPX = "AGE MEMORY PROBLEMS BEGAN - CHILD"
   AFCSUDDEN = "MEM PROBLEM BEGAN SUDDENLY/SLOWLY-CHILD"
   AFCWORSEN = "MEMORY PROBLEMS WORSEN OVER TIME-CHILD"
   AFCLIMITS = "MEM PROB CAUSE DAILY LIMITATIONS-CHILD"
   AFCDRDX = "DR DIAGNOSED CAUSE OF MEM TROUBLE-CHILD"
   AFCDXSPECCD = "MEMORY TROUBLE DIAGNOSIS - CHILD"
   AFCAUTOP = "AUTOPSY PERFORMED ON CHILD"
;
run;
