/* Command file to read ASCII data file into SAS /*
/* Note 1: change SAS library and dataset name as necessary */
LIBNAME ADAMS1'c:\adams1\sas\';
DATA ADAMS1.Adams1AJ_R;

/* Note 2: change location of input data file to match your system */

INFILE 'c:\adams1\data\ADAMS1AJ_R.da' LRECL = 298;
INPUT
   HHID $ 1 - 6
   PN $ 7 - 9
   ADAMSSID $ 10 - 14
   AJNEURCOMP  15 - 15
   AJRANGELAT  16 - 16
   AJRANGEVER  17 - 17
   AJPUPILLAR  18 - 18
   AJOPENJAW  19 - 19
   AJPHARYNGE  20 - 20
   AJCLOSEYES  21 - 21
   AJBLOWOUT  22 - 22
   AJWIDESMIL  23 - 23
   AJEYEBROWS  24 - 24
   AJWINK  25 - 25
   AJTONGUE  26 - 26
   AJMOTOR_A  27 - 27
   AJMOTOR_B  28 - 28
   AJRACOUSTA  29 - 29
   AJLACOUSTA  30 - 30
   AJRWHISPER  31 - 31
   AJLWHISPER  32 - 32
   AJCHIN  33 - 33
   AJSHOULDER  34 - 34
   AJMUTE  35 - 35
   AJREPEAT_A  36 - 36
   AJREPEAT_B  37 - 37
   AJREPEAT_C  38 - 38
   AJRATECONV  39 - 39
   AJCLARCONV  40 - 40
   AJF_NRIGHT  41 - 41
   AJF_NLEFT  42 - 42
   AJRF_TTAPP  43 - 43
   AJLF_TTAPP  44 - 44
   AJRDIADOCH  45 - 45
   AJRDIADCOD  46 - 46
   AJLDIADOCH  47 - 47
   AJLDIADCOD  48 - 48
   AJHAND_A  49 - 49
   AJHAND_B  50 - 50
   AJRGRASP  51 - 51
   AJLGRASP  52 - 52
   AJRMUSCLE  53 - 53
   AJLMUSCLE  54 - 54
   AJRCOGWHL  55 - 55
   AJLCOGWHL  56 - 56
   AJRANKLE  57 - 57
   AJLANKLE  58 - 58
   AJRPROPRIC  59 - 59
   AJLPROPRIC  60 - 60
   AJRVIBRAT  61 - 61
   AJLVIBRAT  62 - 62
   AJRPLANTAR  63 - 63
   AJLPLANTAR  64 - 64
   AJRHEEL  65 - 65
   AJLHEEL  66 - 66
   AJROMBERG  67 - 67
   AJGAIT_A  68 - 68
   AJGAIT_B  69 - 69
   AJGAIT_C  70 - 70
   AJGAIT_D  71 - 71
   AJGAIT_E  72 - 72
   AJTREMOR  73 - 73
   AJTREM_ARM  74 - 74
   AJPRONAT  75 - 75
   AJSTRENGTH  76 - 76
   AJGRIP_BIC  77 - 77
   AJUPPEREXT  78 - 78
   AJBRADYKIN  79 - 79
   AJMYOCLONU  80 - 80
   AJPOSTURE  81 - 81
   AJCOMB  82 - 82
   AJHAMMER  83 - 83
   AJBRUSH  84 - 84
   AJCHKDONE  85 - 85
   AJA1  86 - 86
   AJA2  87 - 87
   AJA3  88 - 88
   AJA4  89 - 89
   AJA5  90 - 90
   AJA6  91 - 91
   AJA7  92 - 92
   AJA8  93 - 93
   AJA1MET  94 - 94
   AJA2MET  95 - 95
   AJA3MET  96 - 96
   AJA4MET  97 - 97
   AJAMET  98 - 98
   AJB1  99 - 99
   AJB2  100 - 100
   AJB3  101 - 101
   AJB4  102 - 102
   AJB5  103 - 103
   AJB6  104 - 104
   AJB7  105 - 105
   AJB8  106 - 106
   AJB9  107 - 107
   AJB1MET  108 - 108
   AJB2MET  109 - 109
   AJB3MET  110 - 110
   AJB4MET  111 - 111
   AJBMET  112 - 112
   AJC1  113 - 113
   AJC2  114 - 114
   AJC3  115 - 115
   AJC4  116 - 116
   AJC5  117 - 117
   AJC1MET  118 - 118
   AJCMET  119 - 119
   AJD1  120 - 120
   AJD2  121 - 121
   AJD3  122 - 122
   AJD4  123 - 123
   AJD5  124 - 124
   AJD6  125 - 125
   AJD1MET  126 - 126
   AJD2MET  127 - 127
   AJDMET  128 - 128
   AJE1  129 - 129
   AJE2  130 - 130
   AJE3  131 - 131
   AJE4  132 - 132
   AJE5  133 - 133
   AJE6  134 - 134
   AJE7  135 - 135
   AJE8  136 - 136
   AJE1MET  137 - 137
   AJE2MET  138 - 138
   AJEMET  139 - 139
   AJF1  140 - 140
   AJF2  141 - 141
   AJF3  142 - 142
   AJF4  143 - 143
   AJF5  144 - 144
   AJF6  145 - 145
   AJF7  146 - 146
   AJF1MET  147 - 147
   AJF2MET  148 - 148
   AJFMET  149 - 149
   AJG1  150 - 150
   AJG2  151 - 151
   AJG3  152 - 152
   AJG4  153 - 153
   AJG5  154 - 154
   AJG6  155 - 155
   AJG7  156 - 156
   AJG1MET  157 - 157
   AJG2MET  158 - 158
   AJGMET  159 - 159
   AJH1  160 - 160
   AJH2  161 - 161
   AJH3  162 - 162
   AJH4  163 - 163
   AJH5  164 - 164
   AJH6  165 - 165
   AJH1MET  166 - 166
   AJHMET  167 - 167
   AJI1  168 - 168
   AJI2  169 - 169
   AJI3  170 - 170
   AJI1MET  171 - 171
   AJIMET  172 - 172
   AJJ1  173 - 173
   AJJ2  174 - 174
   AJJ3  175 - 175
   AJJ1MET  176 - 176
   AJJMET  177 - 177
   AJK1  178 - 178
   AJK2  179 - 179
   AJK3  180 - 180
   AJK1MET  181 - 181
   AJKMET  182 - 182
   AJL1  183 - 183
   AJL2  184 - 184
   AJL3  185 - 185
   AJL4  186 - 186
   AJL1MET  187 - 187
   AJLMET  188 - 188
   AJM1  189 - 189
   AJM2  190 - 190
   AJM3  191 - 191
   AJM4  192 - 192
   AJM1MET  193 - 193
   AJMMET  194 - 194
   AJN1  195 - 195
   AJN2  196 - 196
   AJN3  197 - 197
   AJN4  198 - 198
   AJN1MET  199 - 199
   AJNMET  200 - 200
   AJO1  201 - 201
   AJO2  202 - 202
   AJO3  203 - 203
   AJO1MET  204 - 204
   AJOMET  205 - 205
   AJP1  206 - 206
   AJP2  207 - 207
   AJP3  208 - 208
   AJP1MET  209 - 209
   AJPMET  210 - 210
   AJQ1  211 - 211
   AJQ2  212 - 212
   AJQ3  213 - 213
   AJQ4  214 - 214
   AJQ5  215 - 215
   AJQ1MET  216 - 216
   AJQMET  217 - 217
   AJR1  218 - 218
   AJR2  219 - 219
   AJR3  220 - 220
   AJR1MET  221 - 221
   AJRMET  222 - 222
   AJS1  223 - 223
   AJS2  224 - 224
   AJS3  225 - 225
   AJS1MET  226 - 226
   AJSMET  227 - 227
   AJT1  228 - 228
   AJT2  229 - 229
   AJT3  230 - 230
   AJT4  231 - 231
   AJT1MET  232 - 232
   AJTMET  233 - 233
   AJU1  234 - 234
   AJU2  235 - 235
   AJU3  236 - 236
   AJU4  237 - 237
   AJU5  238 - 238
   AJU6  239 - 239
   AJU7  240 - 240
   AJU8  241 - 241
   AJU9  242 - 242
   AJU10  243 - 243
   AJU11  244 - 244
   AJU12  245 - 245
   AJU1MET  246 - 246
   AJU2MET  247 - 247
   AJUMET  248 - 248
   AJV1  249 - 249
   AJV2  250 - 250
   AJV3  251 - 251
   AJV1MET  252 - 252
   AJVMET  253 - 253
   AJW1  254 - 254
   AJW2  255 - 255
   AJW3  256 - 256
   AJW1MET  257 - 257
   AJWMET  258 - 258
   AJX1  259 - 259
   AJX2  260 - 260
   AJX1MET  261 - 261
   AJXMET  262 - 262
   AJY1  263 - 263
   AJY2  264 - 264
   AJY3  265 - 265
   AJY4  266 - 266
   AJY5  267 - 267
   AJY6  268 - 268
   AJY7  269 - 269
   AJY8  270 - 270
   AJY9  271 - 271
   AJY10  272 - 272
   AJY1MET  273 - 273
   AJY2MET  274 - 274
   AJY3MET  275 - 275
   AJY4MET  276 - 276
   AJY5MET  277 - 277
   AJYMET  278 - 278
   AJZ1  279 - 279
   AJZ2  280 - 280
   AJZ3  281 - 281
   AJZ4  282 - 282
   AJZ5  283 - 283
   AJZ6  284 - 284
   AJZ7  285 - 285
   AJZ8  286 - 286
   AJZ9  287 - 287
   AJZ10  288 - 288
   AJZ11  289 - 289
   AJZ12  290 - 290
   AJZ1MET  291 - 291
   AJZ2MET  292 - 292
   AJZMET  293 - 293
   AJAA1  294 - 294
   AJAA2  295 - 295
   AJAA3  296 - 296
   AJAA1MET  297 - 297
   AJAAMET  298 - 298
;

LABEL
   HHID = "HOUSEHOLD IDENTIFIER"
   PN = "PERSON NUMBER"
   ADAMSSID = "ADAMS SUBJECT IDENTIFIER"
   AJNEURCOMP = "WHETHER NEUROLLOGICAL EXAM COMPLETED"
   AJRANGELAT = "NEUROLOGICAL EXAM - RANGE, EXTENT OF LATERAL GAZE"
   AJRANGEVER = "NEUROLOGICAL EXAM - RANGE,EXTENT OF VERTICAL GAZE"
   AJPUPILLAR = "NEUROLOGICAL EXAM - PUPILLARY REFLEX"
   AJOPENJAW = "NEUROLOGICAL EXAM - OPENING AND CLOSING JAW"
   AJPHARYNGE = "NEUROLOGICAL EXAM - PHARYNGEAL MOVEMENTS"
   AJCLOSEYES = "NEUROLOGICAL EXAM - CLOSE EYES, RESIST OPENING"
   AJBLOWOUT = "NEUROLOGICAL EXAM - BLOW OUT CHEEKS WITH MOUTH CLOSED"
   AJWIDESMIL = "NEUROLOGICAL EXAM - WIDE SMILE, SHOW TEETH"
   AJEYEBROWS = "NEUROLOGICAL EXAM - RAISE EYEBROWS"
   AJWINK = "NEUROLOGICAL EXAM - WINK WITH OTHER EYE OPEN"
   AJTONGUE = "NEUROLOGICAL EXAM - RAPID TONGUE MOVEMENT"
   AJMOTOR_A = "NEUROLOGICAL EXAM - EYE CLOSURE X20 SECS"
   AJMOTOR_B = "NEUROLOGICAL EXAM - TONGUE PROTRUSION X20 SECS"
   AJRACOUSTA = "NEUROLOGICAL EXAM - RUBBING OF FINGERS, RIGHT"
   AJLACOUSTA = "NEUROLOGICAL EXAM - RUBBING OF FINGERS, LEFT"
   AJRWHISPER = "NEUROLOGICAL EXAM - WHISPERING, RIGHT"
   AJLWHISPER = "NEUROLOGICAL EXAM - WHISPERING, LEFT"
   AJCHIN = "NEUROLOGICAL EXAM - CHIN RESISTANCE"
   AJSHOULDER = "NEUROLOGICAL EXAM - SHOULDER ELEVATION, SHRUG"
   AJMUTE = "NEUROLOGICAL EXAM - WHETHER SUBJECT IS MUTE"
   AJREPEAT_A = "NEUROLOGICAL EXAM - REPEAT LA,LA,LA"
   AJREPEAT_B = "NEUROLOGICAL EXAM - REPEAT GO,GO,GO"
   AJREPEAT_C = "NEUROLOGICAL EXAM - REPEAT KITTY,KITTY,KITTY"
   AJRATECONV = "NEUROLOGICAL EXAM - RATE OF CONVERSATION"
   AJCLARCONV = "NEUROLOGICAL EXAM - CLARITY OF CONVERSATION"
   AJF_NRIGHT = "NEUROLOGICAL EXAM - FINGER TO NOSE TOUCH, RIGHT REV"
   AJF_NLEFT = "NEUROLOGICAL EXAM - FINGER TO NOSE TOUCH, LEFT REV"
   AJRF_TTAPP = "NEUROLOGICAL EXAM - FINGER THUMB TAPPING, RIGHT"
   AJLF_TTAPP = "NEUROLOGICAL EXAM - FINGER THUMB TAPPING, LEFT"
   AJRDIADOCH = "NEUROLOGICAL EXAM - DIADOCHOKINESIS, RIGHT"
   AJRDIADCOD = "NEUROLOGICAL EXAM - DIADOCHOKINESIS ABNORM CODE RIGHT"
   AJLDIADOCH = "NEUROLOGICAL EXAM - DIADOCHOKINESIS, LEFT"
   AJLDIADCOD = "NEUROLOGICAL EXAM - DIADOCHOKINESIS ABNORM CODE LEFT"
   AJHAND_A = "NEUROLOGICAL EXAM - INTERLOCKING THUMBS"
   AJHAND_B = "NEUROLOGICAL EXAM - MIRRORED FINGERS"
   AJRGRASP = "NEUROLOGICAL EXAM - GRASP, RIGHT"
   AJLGRASP = "NEUROLOGICAL EXAM - GRASP, LEFT"
   AJRMUSCLE = "NEUROLOGICAL EXAM - MUSCLE TONUS, ELBOW,WRIST, RIGHT"
   AJLMUSCLE = "NEUROLOGICAL EXAM - MUSCLE TONUS, ELBOW,WRIST, LEFT"
   AJRCOGWHL = "NEUROLOGICAL EXAM - COGWHEEL PHENOMENON, RIGHT"
   AJLCOGWHL = "NEUROLOGICAL EXAM - COGWHEEL PHENOMENON, LEFT"
   AJRANKLE = "NEUROLOGICAL EXAM - ANKLE CLONUS, RIGHT"
   AJLANKLE = "NEUROLOGICAL EXAM - ANKLE CLONUS, LEFT"
   AJRPROPRIC = "NEUROLOGICAL EXAM - PROPRIOCEPTION, RIGHT"
   AJLPROPRIC = "NEUROLOGICAL EXAM - PROPRIOCEPTION, LEFT"
   AJRVIBRAT = "NEUROLOGICAL EXAM - VIBRATING SENSATION, RIGHT"
   AJLVIBRAT = "NEUROLOGICAL EXAM - VIBRATING SENSATION, LEFT"
   AJRPLANTAR = "NEUROLOGICAL EXAM - PLANTAR RESPONSE, RIGHT"
   AJLPLANTAR = "NEUROLOGICAL EXAM - PLANTAR RESPONSE, LEFT"
   AJRHEEL = "NEUROLOGICAL EXAM - HEEL TO KNEE TEST, RIGHT"
   AJLHEEL = "NEUROLOGICAL EXAM - HEEL TO KNEE TEST, LEFT"
   AJROMBERG = "NEUROLOGICAL EXAM - ROMBERGS SIGN"
   AJGAIT_A = "NEUROLOGICAL EXAM - WALK HALL 10 PACES"
   AJGAIT_B = "NEUROLOGICAL EXAM - PIVOT WHILE TURNING"
   AJGAIT_C = "NEUROLOGICAL EXAM - STOPPING ON UNEXPECTED COMMAND"
   AJGAIT_D = "NEUROLOGICAL EXAM - FESTINATION"
   AJGAIT_E = "NEUROLOGICAL EXAM - ACCESSORY MOVEMENTS"
   AJTREMOR = "NEUROLOGICAL EXAM - TREMOR AT REST"
   AJTREM_ARM = "NEUROLOGICAL EXAM - TREMOR ARMS OUTSTRETCHED"
   AJPRONAT = "NEUROLOGICAL EXAM - PRONATOR DRIFT"
   AJSTRENGTH = "NEUROLOGICAL EXAM - STRENGTH DIFFERENCE, DOWN PRESSURE"
   AJGRIP_BIC = "NEUROLOGICAL EXAM - UPPER EXTREMITY, WHICH TEST"
   AJUPPEREXT = "NEUROLOGICAL EXAM - UPPER EXTREMITY MOTOR STRENGTH"
   AJBRADYKIN = "NEUROLOGICAL EXAM - BRADYKENESIA"
   AJMYOCLONU = "NEUROLOGICAL EXAM - MYOCLONUS"
   AJPOSTURE = "NEUROLOGICAL EXAM - POSTURE"
   AJCOMB = "NEUROLOGICAL EXAM - PRAXIS, COMB YOUR HAIR"
   AJHAMMER = "NEUROLOGICAL EXAM - PRAXIS, HAMMER A NAIL"
   AJBRUSH = "NEUROLOGICAL EXAM - PRAXIS, BRUSH YOUR TEETH"
   AJCHKDONE = "WHETHER DEMENTIA CHECKLIST COMPLETED"
   AJA1 = "DEMENTIA, DSM IV, MEM IMPAIRMENT"
   AJA2 = "DEMENTIA, DSM IV, APHASIA"
   AJA3 = "DEMENTIA, DSM IV, APRAXIA"
   AJA4 = "DEMENTIA, DSM IV, AGNOSIA"
   AJA5 = "DEMENTIA, DSM IV, EXEC FUNCTION DISTURBANCE"
   AJA6 = "DEMENTIA, DSM IV, SOCIAL OR OCCUP IMPAIRMENT"
   AJA7 = "DEMENTIA, DSM IV, SIGNIFICANT DECLINE"
   AJA8 = "DEMENTIA, DSM IV, COG DEFICITS DURING DELIRIUM"
   AJA1MET = "DEMENTIA - CRITERIA FOR CKA1"
   AJA2MET = "DEMENTIA -  CRITERIA FOR CKA2 - CKA5"
   AJA3MET = "DEMENTIA - CRITERIA FOR CKA6 AND CKA7"
   AJA4MET = "DEMENTIA - CRITERIA FOR CKA8"
   AJAMET = "DEMENTIA - WHETHER OVERALL DSM IV CRITERIA MET"
   AJB1 = "DEMENTIA, DSM III R, SHORT TERM MEMORY"
   AJB2 = "DEMENTIA, DSM III R, LONG TERM MEMORY"
   AJB3 = "DEMENTIA, DSM III R, ABSTRACT THINKING"
   AJB4 = "DEMENTIA, DSM III R, JUDGEMENT"
   AJB5 = "DEMENTIA, DSM III R, OTHER HIGHER CORTICAL FUNCTIONING"
   AJB6 = "DEMENTIA, DSM III R, PERSONALITY CHANGE"
   AJB7 = "DEMENTIA, DSM III R, SOCIAL OR OCCUP IMPAIRMENT"
   AJB8 = "DEMENTIA, DSM III R, SIGNIFICANT DECLINE"
   AJB9 = "DEMENTIA, DSM III R, COG DEFICITS DURING DELIRIUM"
   AJB1MET = "DEMENTIA, DSM III R - CRITERIA FOR CKB1 AND CKB2"
   AJB2MET = "DEMENTIA, DSM III R - CRITERIA FOR CKB3 - CKB6"
   AJB3MET = "DEMENTIA, DSM III R - CRITERIA FOR CKB7 AND CKB8"
   AJB4MET = "DEMENTIA, DSM III R - CRITERIA FOR CKB9"
   AJBMET = "DEMENTIA, DSM III R - WHETHER OVERALL DSM III R CRITERIA MET"
   AJC1 = "PROB AD, DEMENTIA, ESTABLISHED BY CKAMET OR CKBMET"
   AJC2 = "PROB AD, PROGRESSION OF COGNITIVE SYMPTOMS"
   AJC3 = "PROB AD, ABSENCE OF OTHER CONDITIONS SUFFICIENT TO CAUSE DEM"
   AJC4 = "PROB AD, RPT OF MED EVAL TO RULE OUT OTHER CAUSES OF DEMENTIA"
   AJC5 = "PROB AD, ONSET AFTER AGE 40"
   AJC1MET = "PROB AD - CRITERIA FOR CKC1 - CKC5"
   AJCMET = "PROB AD - CRITERIA FOR CKC1MET"
   AJD1 = "POSS AD - CRITERIA FOR CKAMET OR CKBMET"
   AJD2 = "POSS AD, PROGRESSION OF COGNITIVE SYMPTOMS"
   AJD3 = "POSS AD, ONSET AFTER AGE 40"
   AJD4 = "POSS AD, ATYPICAL ONSET, PRESENTATION OR PROGRESSION"
   AJD5 = "POSS AD, PRESENCE OF SYSTEMIC OR BRAIN DISORDER, NOT SOLE CA"
   AJD6 = "POSS AD, NO RPT OF MED EVAL TO RULE OUT OTHER DEM"
   AJD1MET = "POSS AD - CRITERIA FOR CKD1 - CKD3"
   AJD2MET = "POSS AD - CRITERIA FOR CKD4 - CKD6"
   AJDMET = "POSS AD - CRITERIA FOR CKD1MET AND CKD2MET"
   AJE1 = "PROB VASC DEM - CRITERIA FOR CKAMET OR CKBMET"
   AJE2 = "PROB VASC DEM, IMPAIRMENT IN MEM AND 2 OTHER COG DOMAINS"
   AJE3 = "PROB VASC DEM, SOCIAL OR OCCUP IMPAIRMENT"
   AJE4 = "PROB VASC DEM, CVD BASED ON HIST OR EXAM"
   AJE5 = "PROB VASC DEM, EVIDENCE OF RELEVANT CVD NOTED ON BRAIN IMAGI"
   AJE6 = "PROB VASC DEM, ONSET OF DEM WITHIN 3 MOS OF STROKE"
   AJE7 = "PROB VASC DEM, DETERIORATION IN FUNCTION"
   AJE8 = "PROB VASC DEM, SPECIFIC BRAIN IMAGING INDICATE DAMAGE"
   AJE1MET = "PROB VASC DEM - CRITERIA FOR CKE1 - CKE5"
   AJE2MET = "PROB VASC DEM - CRITERIA FOR CKE6, CKE7, OR CKE8"
   AJEMET = "PROB VASC DEM - CRITERIA FOR CKE1MET AND CKE2MET"
   AJF1 = "POSS VASC DEM, EST BY CKAMET OR CKBMET"
   AJF2 = "POSS VASC DEM, IMPAIRMENT IN MEM AND 2 OTHER COG DOMAINS"
   AJF3 = "POSS VASC DEM, SOCIAL OR OCCUP IMPAIRMENT"
   AJF4 = "POSS VASC DEM, CVD BASED ON HIST OR EXAM"
   AJF5 = "POSS VASC DEM, BRAIN IMAGING HAS NOT BEEN DONE"
   AJF6 = "POSS VASC DEM, UNCLEAR REL BET STROKE AND DEMENTIA"
   AJF7 = "POSS VASC DEM, SUBTLE ONSET AND VARIABLE COURSE OF COG DEFICITS"
   AJF1MET = "PROB VASC DEM - CRITERIA FOR CKF1 - CKF4"
   AJF2MET = "PROB VASC DEM - CRITERIA FOR CKF5 - CKF7"
   AJFMET = "PROB VASC DEM - CRITERIA FOR CKF1MET AND CKF2MET"
   AJG1 = "CIND, SHORT TERM OR LONG TERM MEMORY IMPAIRMENT"
   AJG2 = "CIND, EXECUTIVE FUNCTION"
   AJG3 = "CIND, LANGUAGE"
   AJG4 = "CIND, PRAXIS"
   AJG5 = "CIND, ORIENTATION"
   AJG6 = "CIND, BASED ON DSRS SCORE"
   AJG7 = "CIND, DOES NOT MEET CRITERIA FOR CKAMET OR CKBMET"
   AJG1MET = "CIND - CRITERIA FOR CKG1 - CKG6"
   AJG2MET = "CIND - CRITERIA FOR CKG7"
   AJGMET = "CIND - CRITERIA FOR CKG1MET AND CKG2MET"
   AJH1 = "MCI, MEMORY COMPLAINT BY INFORMANT"
   AJH2 = "MCI, MEMORY IMPAIRMENT BY MEASUREMENT ON MEMORY TASKS"
   AJH3 = "MCI, BASED ON MMSE SCORE"
   AJH4 = "MCI, BASED ON CDR MEMORY SCORE AND OVERALL CDR"
   AJH5 = "MCI, NOT DUE TO MCKOR DEPRESSION"
   AJH6 = "MCI, MEETS CRITERIA FOR CIND"
   AJH1MET = "MCI - CRITERIA FOR CKH1 - CKH6"
   AJHMET = "MCI - CRITERIA FOR CKH1MET"
   AJI1 = "MAJOR DEPRESSION BASED ON NPI, CIDI, OR CLINICAL OR MEDICAL HISTORY"
   AJI2 = "DEPRESSION, IMPAIRMENT NOT EXPLAINED BY OTHER ETIOLOGY"
   AJI3 = "DEPRESSION, MEETS CRITERIA FOR CIND"
   AJI1MET = "DEPRESSION - CRITERIA FOR CKI1, CKI2, AND CKI3"
   AJIMET = "DEPRESSION - CRITERIA FOR CKI1MET"
   AJJ1 = "NEUROPSYCHIATRIC DISORDER  - CLINICAL OR MEDICAL HISTORY"
   AJJ2 = "NEUROPSYCHIATRIC DISORDER, NOT OTHERWISE EXPLAINED"
   AJJ3 = "NEUROPSYCHIATRIC DISORDER, MEETS CRITERIA FOR CIND"
   AJJ1MET = "NEUROPSYCHIATRIC DISORDER, CRITERIA FOR CKJ1 - CKJ3"
   AJJMET = "NEUROPSYCHIATRIC DISORDER, CRITERIA FOR CKJ1MET"
   AJK1 = "LIFELONG HISTORY OF MENT RET, LD, LOW BASELINE INTELLECT"
   AJK2 = "MENT RET, LD, LOW BASELINE INTELLECT NOT EXPLAINED BY OTHER ETIOLOGY"
   AJK3 = "MENT RET, LD, LOW BASELINE INTELLECT, MEETS CRITERIA FOR CIND"
   AJK1MET = "MENT RET, LD, LOW BASELINE INTELLECT - CRITERIA FOR CKK1 - CKK3"
   AJKMET = "MENT RET, LD, LOW BASELINE INTELLECT - CRITERIA FOR AKJMET"
   AJL1 = "HISTORY OF PAST ALCOHOL ABUSE"
   AJL2 = "ALCOHOL ABUSE PAST, DISCONTINUED AT LEAST SIX MONTHS PRIOR TO EVAL"
   AJL3 = "PAST ALCOHOL ABUSE, NOT EXPLAINED BY OTHER ETIOLOGY"
   AJL4 = "PAST ALCOHOL ABUSE, MEETS CRITERIA FOR CIND"
   AJL1MET = "PAST ALCOHOL ABUSE - CRITERIA FOR CKL1 - CKL4"
   AJLMET = "PAST ALCOHOL ABUSE - CRITERIA FOR CKL1MET"
   AJM1 = "HISTORY OF PAST AND CURRENT ALCOHOL ABUSE"
   AJM2 = "HAS ABUSED ALCOHOL IN THE PAST SIX MONTHS"
   AJM3 = "CURRENT ALCOHOL ABUSE, NOT EXPLAINED BY OTHER ETIOLOGY"
   AJM4 = "CURRENT ALCOHOL ABUSE, MEETS CRITERIA FOR CIND"
   AJM1MET = "CURRENT ALCOHOL ABUSE - CRITERIA FOR CKM1 - CKM4"
   AJMMET = "CURRENT ALCOHOL ABUSE - CRITERIA FOR CKM1MET"
   AJN1 = "STROKE HIST BASED ON CLINICAL, MED HISTORY, OR NEUROLOGICAL EXAM"
   AJN2 = "STROKE SYMPTOM ONSET WITHIN THREE MONTHS AFTER REPORTED STROKE"
   AJN3 = "STROKE, IMPAIRMENT NOT EXPLAINED BY OTHER ETIOLOGY"
   AJN4 = "STROKE, MEETS CRITERIA FOR CIND"
   AJN1MET = "STROKE - CRITERIA FOR CKN1 - CKN4"
   AJNMET = "STROKE - CRITERIA FOR CKN1MET"
   AJO1 = "OTHER NEUROL COND, PRESENCE OF NEUROLOGICAL CONDITION"
   AJO2 = "OTHER NEUROL COND, NOT EXPLAINED BY OTHER ETIOLOGY"
   AJO3 = "OTHER NEUROL COND, MEETS CRITERIA FOR CIND"
   AJO1MET = "OTHER NEUROL COND - CRITERIA FOR CKO1 - CKO3"
   AJOMET = "OTHER NEUROL COND - CRITERIA FOR CKO1MET"
   AJP1 = "OTHER MEDICAL COND, PRESENCE OF MEDICAL CONDITION"
   AJP2 = "OTHER MEDICAL COND, NOT EXPLAINED BY OTHER ETIOLOGY"
   AJP3 = "OTHER MEDICAL COND, MEETS CRITERIA FOR CIND"
   AJP1MET = "OTHER MEDICAL COND - CRITERIA FOR CKP1 - CKP3"
   AJPMET = "OTHER MEDICAL COND - CRITERIA FOR CKP1MET"
   AJQ1 = "PRESENCE OF CEREBROVASCULAR OR CARDIOVASCULAR CONDITIONS"
   AJQ2 = "IMPAIRMENT NOT LINKED TO ONE FOCAL VASCULAR LESION"
   AJQ3 = "GRADUAL ONSET OF CEREBROVASCULAR OR CARDIOVASCULAR SYMPTOMS"
   AJQ4 = "CIND SECONDARY TO VASCULAR DISEASE, NOT EXPLAINED BY OTHER ETIOLOGY"
   AJQ5 = "CIND SECONDARY TO VASCULAR DISEASE, MEETS CIND CRITERIA"
   AJQ1MET = "CIND SECONDARY TO VASCULAR DISEASE, CRITERIA FOR CKQ1 - CKQ5"
   AJQMET = "CIND SECONDARY TO VASC DISEASE - CRITERIA FOR CKQ1MET"
   AJR1 = "MILD AMBIGUOUS, IMPAIRMENT NOT EXPLAINED BY ETIOLOGY IN CIND"
   AJR2 = "MILD AMBIGUOUS, GRADUAL ONSET AND PROGRESSION OF SYMPTOMS"
   AJR3 = "MILD AMBIGUOUS, MEETS CRITERIA FOR CIND"
   AJR1MET = "MILD AMBIGUOUS - CRITERIA FOR CKR1 - CKR3"
   AJRMET = "MILD AMBIGUOUS - CRITERIA FOR CKR1MET"
   AJS1 = "DEM UNDETERMINED ETIOLOGY, EST BY DSM III OR DSM IV CRITERIA"
   AJS2 = "DEMENTIA UNDETERMINED ETIOLOGY PROGRESSION OF SYMPTOMS OVER TIME"
   AJS3 = "DEMENTIA UNDETERMINED ETIOLOGY, ATYPICAL FEATURES"
   AJS1MET = "DEMENTIA UNDETERMINED ETIOLOGY - CRITERIA FOR CKS1 - CKS3"
   AJSMET = "DEMENTIA UNDETERMINED ETIOLOGY - CRITERIA FOR CKS1MET"
   AJT1 = "PD, DEM ESTABLISHED BY DSM III OR DSM IV CRITERIA"
   AJT2 = "PD, DIAGNOSIS OF PD"
   AJT3 = "PD, COG SYMPTOMS PRIMARILY SUBCORTICAL"
   AJT4 = "PD, ONSET OF COG SYMPTOMS AT LEAST 1 YR PAST MOTOR SYMPTOMS"
   AJT1MET = "PD - CRITERIA FOR CKT1 - CKT4"
   AJTMET = "PD - CRITERIA FOR CKT1MET"
   AJU1 = "PROB LEWY BODY DEMENTIA EST BY DSM III OR DSM IV CRITERIA"
   AJU2 = "PROB LEWY BODY DEMENTIA, FLUCTUATING COGNITION"
   AJU3 = "PROB LEWY BODY DEMENTIA, RECURRENT VISUAL HALLUCINATIONS"
   AJU4 = "PROB LEWY BODY DEMENTIA, MOTOR FEATURES OF PARKINSONISM"
   AJU5 = "PROB LEWY BODY DEMENTIA, REPEATED FALLS"
   AJU6 = "PROB LEWY BODY DEMENTIA, SYNCOPE"
   AJU7 = "PROB LEWY BODY DEMENTIA, LOSS OF CONSCIOUSNESS"
   AJU8 = "PROB LEWY BODY DEMENTIA, NEUROLEPTIC SENSITIVITY"
   AJU9 = "PROB LEWY BODY DEMENTIA, SYSTEMATIZED DELUSIONS"
   AJU10 = "PROB LEWY BODY DEMENTIA, OTHER MODAL HALLUCINATIONS"
   AJU11 = "PROB LEWY BODY DEMENTIA, REM SLEEP DISORDER"
   AJU12 = "PROB LEWY BODY DEMENTIA, DEPRESSIVE SYMPTOMS"
   AJU1MET = "PROB LEWY BODY DEMENTIA - CRITERIA FOR CKU1"
   AJU2MET = "PROB LEWY BODY DEMENTIA - CRITERIA FOR CKU2 - CKU4"
   AJUMET = "PROB LEWY BODY DEM - CRITERIA FOR CKU1MET AND CKU2MET"
   AJV1 = "PSP, DEMENTIA EST BY DSM III OR DSM IV CRITERIA"
   AJV2 = "PSP, IMPAIRMENT OF VOLUNTARY DOWNWARD GAZE"
   AJV3 = "PSP, IMPAIRMENT NOT EXPLAINED BY ANOTHER DEMENTIA TYPE"
   AJV1MET = "PSP, CRITERIA FOR CKV1 - CKV3"
   AJVMET = "PSP, CRITERIA FOR CKV1MET"
   AJW1 = "NORMAL PRESSURE HYDROCEPHALUS, EST BY DSM III OR DSM IV CRITERIA"
   AJW2 = "NORMAL PRESSURE HYDROCEPHALUS, REPORT FROM NEUROIMAGING"
   AJW3 = "NORMAL PRESSURE HYDROCEPHALUS, NOT EXPLAINED BY OTHER DEMENTIA TYPE"
   AJW1MET = "NORMAL PRESSURE HYDROCEPHALUS, CRITERIA FOR CKW1 - CKW3"
   AJWMET = "NORMAL PRESSURE HYDROCEPHALUS - CRITERIA FOR CKW1MET"
   AJX1 = "HUNTINGTONS DEMENTIA, EST BY DSM III OR DSM IV CRITERIA"
   AJX2 = "HUNTINGTONS, DIAGNOSIS OF HUNTINGTONS DISEASE"
   AJX1MET = "HUNTINGTONS DEMENTIA, CRITERIA FOR CKX1 AND CKX2"
   AJXMET = "HUNTINGTONS DEMENTIA, CRITERIA FOR CKX1MET"
   AJY1 = "FRONTAL LOBE, INSIDIOUS ONSET AND SLOWLY PROGRESSIVE"
   AJY2 = "FRONTAL LOBE, PROFOUND FAILURE ON FRONTAL LOBE TESTS"
   AJY3 = "FRONTAL LOBE, PERCEPTUAL SPATIAL DISORDERS ARE ABSENT"
   AJY4 = "FRONTAL LOBE, UNIQUE SPEECH DISTURBANCES"
   AJY5 = "FRONTAL LOBE, COMMON AFFECTIVE SYMPTOMS"
   AJY6 = "FRONTAL LOBE SIGNS AND OTHER PHYSICAL SIGNS"
   AJY7 = "FRONTAL LOBE, NORMAL EEG"
   AJY8 = "FRONTAL LOBE, BRAIN IMAGING"
   AJY9 = "FRONTAL LOBE, OTHER SUPPORTIVE DIAGNOSTIC FEATURES"
   AJY10 = "FRONTAL LOBE, EXCLUSIONARY FEATURES (LIST)"
   AJY1MET = "FRONTAL LOBE, CRITERIA FOR CKY1"
   AJY2MET = "FRONTAL LOBE, CRITERIA FOR CKY2"
   AJY3MET = "FRONTAL LOBE, CRITERIA FOR CKY3"
   AJY4MET = "FRONTAL LOBE, CRITERIA FOR CKY4"
   AJY5MET = "FRONTAL LOBE, CRITERIA FOR CKY10"
   AJYMET = "FRONTAL LOBE - CRITERIA FOR CKY1MET - CKY5MET"
   AJZ1 = "POSS LEWY BODY DEMENTIA EST BY DSM III OR DSM IV CRITERIA"
   AJZ2 = "POSS LEWY BODY DEMENTIA, FLUCTUATING COGNITION"
   AJZ3 = "POSS LEWY BODY DEMENTIA, RECURRENT VISUAL HALLUCINATIONS"
   AJZ4 = "POSS LEWY BODY DEMENTIA, MOTOR FEATURES OF PARKINSONISM"
   AJZ5 = "POSS LEWY BODY DEMENTIA, REPEATED FALLS"
   AJZ6 = "POSS LEWY BODY DEMENTIA, SYNCOPE"
   AJZ7 = "POSS LEWY BODY DEMENTIA, LOSS OF CONSCIOUSNESS"
   AJZ8 = "POSS LEWY BODY DEMENTIA, NEUROLEPTIC SENSITIVITY"
   AJZ9 = "POSS LEWY BODY DEMENTIA, SYSTEMATIZED DELUSIONS"
   AJZ10 = "POSS LEWY BODY DEMENTIA, OTHER MODAL HALLUCINATIONS"
   AJZ11 = "POSS LEWY BODY DEMENTIA, REM SLEEP DISORDER"
   AJZ12 = "POSS LEWY BODY DEMENTIA, DEPRESSIVE SYMPTOMS"
   AJZ1MET = "POSS LEWY BODY DEMENTIA - CRITERIA FOR CKZ1"
   AJZ2MET = "POSS LEWY BODY DEMENTIA - CRITERIA FOR CKZ2 - CKZ4"
   AJZMET = "POSS LEWY BODY DEMENTIA - CRITERIA FOR CKZ1MET AND CKZ2MET"
   AJAA1 = "SEVERE HEAD TRAUMA, DEM ESTABLISHED BY CKAMET OR CKBMET"
   AJAA2 = "SEVERE HEAD TRAUMA, SEVERE COGNITIVE SEQUELAE"
   AJAA3 = "SEVERE HEAD TRAUMA, IMPAIRMENT NOT OTHERWISE EXPLAINED"
   AJAA1MET = "SEVERE HEAD TRAUMA - CRITERIA FOR CKAA1 - CKAA3"
   AJAAMET = "SEVERE HEAD TRAUMA - CRITERIA FOR CKAA1MET"
;
run;
